# Generated by Django 5.0.1 on 2024-01-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_remove_document_user_document_keywords_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
