# Generated by Django 4.1.7 on 2024-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
